- name: Main Playbook
  hosts: all
  gather_facts: yes

  vars:
    static_playbook_dir: "{{ playbook_dir }}"

  tasks:
    - name: Setup
      include_tasks: setup.yml

    - name: Git Configuration
      include_tasks: github/git_configuration.yml

    - name: Docker Setup
      include_tasks: docker/docker_setup.yml

    - name: Project Service
      include_tasks: project_service.yml

    - name: Cleanup
      include_tasks: cleanup.yml