- name: Setup Docker and Docker Compose on Ubuntu
  hosts: all
  gather_facts: yes

  vars:
    github_project_url: "{{ lookup('env', 'GITHUB_PROJECT_URL') }}"
    github_username: "{{ lookup('env', 'GITHUB_USERNAME') }}"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    static_playbook_dir: "{{playbook_dir}}"

  tasks:

    - name: Set project_dest_dir variable
      set_fact:
        project_dest_dir: "{{ static_playbook_dir }}/project"

    - name: Set project_repo_url variable
      set_fact:
        project_repo_url: "{{ github_project_url }}"
    
    - name: Configure Git with GitHub token
      shell: |
        git config --global credential.helper store
        echo "https://{{ github_username }}:{{ github_token }}@github.com" > ~/.git-credentials
      become: yes
    
    - name: Remove existing Project repository if present
      file:
        path: "{{ project_dest_dir }}"
        state: absent
        force: yes
      become: yes

    - name: Clone the Project repository
      git:
        repo: "{{ project_repo_url }}"
        dest: "{{ project_dest_dir }}"
        version: main
      become: yes

    - name: Set service_file_path variable
      set_fact:
        service_file_path: /etc/systemd/system/project.service

    - name: Adding Docker and Compose packages
      include_tasks: docker/install_docker_and_compose.yml

    - name: Create Docker Service
      include_tasks: docker/create_docker_service.yml

    - name: Enable and start project service
      ansible.builtin.systemd:
        name: project
        state: started
        enabled: yes
      become: yes
      ignore_errors: yes