- name: Setup Docker and Docker Compose on Ubuntu
  hosts: all
  gather_facts: yes

  vars:
    static_playbook_dir: "{{ playbook_dir }}"

  tasks:
    - name: Set project_dest_dir variable
      set_fact:
        project_dest_dir: "{{ static_playbook_dir }}/project"
    
    - name: Configure Git with GitHub token
      shell: |
        git config --global credential.helper store
        echo "https://{{ GITHUB_USERNAME }}:{{ GITHUB_TOKEN }}@github.com" > ~/.git-credentials
      become: yes
    
    - name: Remove existing Project repository if present
      file:
        path: "{{ project_dest_dir }}"
        state: absent
        force: yes
      become: yes

    - name: Clone the Project repository
      git:
        repo: "{{ GITHUB_PROJECT_URL }}"
        dest: "{{ project_dest_dir }}"
        version: main
      become: yes

    - name: Set service_file_path variable
      set_fact:
        service_file_path: /etc/systemd/system/project.service

    - name: Adding Docker and Compose packages
      include_tasks: docker/install_docker_and_compose.yml

    - name: Create Docker Service
      include_tasks: docker/create_docker_service.yml

    - name: Enable and start project service
      ansible.builtin.systemd:
        name: project
        state: started
        enabled: yes
      become: yes
      ignore_errors: yes

    # Cleanup section
    - name: Remove GitHub credentials from git-credentials
      file:
        path: ~/.git-credentials
        state: absent
      become: yes

    - name: Clear Git credential helper configuration
      shell: git config --global --unset credential.helper
      become: yes

    - name: Unset environment variables
      shell: |
        unset GITHUB_PROJECT_URL
        unset GITHUB_USERNAME
        unset GITHUB_TOKEN
      environment:
        GITHUB_PROJECT_URL: "{{ GITHUB_PROJECT_URL }}"
        GITHUB_USERNAME: "{{ GITHUB_USERNAME }}"
        GITHUB_TOKEN: "{{ GITHUB_TOKEN }}"
