- name: Create Docker Service
  block:
    - name: Check if Docker Service File Exists
      ansible.builtin.stat:
        path: "{{ service_file_path }}"
      register: service_file_stat

    - name: Remove Existing Docker Service File
      ansible.builtin.file:
        path: "{{ service_file_path }}"
        state: absent
      when: service_file_stat.stat.exists

    - name: Create Docker Service File
      ansible.builtin.file:
        path: "{{ service_file_path }}"
        state: touch
        mode: '0644'
        
    - name: Insert Docker Service Configuration
      ansible.builtin.blockinfile:
        path: "{{ service_file_path }}"
        block: |
          [Unit]
          Description=Project Docker Container
          After=network.target

          [Service]
          User=root
          Group=root
          WorkingDirectory={{ project_dest_dir }}
          ExecStart=docker compose up -d
          Restart=always
          RestartSec=10s
          StandardOutput=journal
          StandardError=journal

          [Install]
          WantedBy=multi-user.target

    - name: Reload Systemd Daemon
      ansible.builtin.systemd:
        daemon_reload: yes

  become: yes
