name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Make install
      run: |
        sudo apt install make

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine setuptools

    - name: Configure Git
      run: |
        git config --global user.email "thesunnysinha@gmail.com"
        git config --global user.name "Sunny Kumar Sinha"

    - name: Make push_to_pypi.sh executable
      run: |
        make clean
        make build
        make upload
